In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("train.csv")

In [4]:
df.head()

,id,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,0,5,8,5,8,6,4,4,3,3,...,5,3,3,5,4,7,5,7,3,0.445
1,1,6,7,4,4,8,8,3,5,4,...,7,2,0,3,5,3,3,4,3,0.450
2,2,6,5,6,7,3,7,1,5,4,...,7,3,7,5,6,8,2,3,3,0.530
3,3,3,4,6,5,4,8,4,7,6,...,2,4,7,4,4,6,5,7,5,0.535
4,4,5,3,2,6,4,4,3,3,3,...,2,2,6,6,4,1,2,3,5,0.415

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1117957 entries, 0 to 1117956
Data columns (total 22 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   id                               1117957 non-null  int64
 1   MonsoonIntensity                 1117957 non-null  int64
 2   TopographyDrainage               1117957 non-null  int64
 3   RiverManagement                  1117957 non-null  int64
 4   Deforestation                    1117957 non-null  int64
 5   Urbanization                     1117957 non-null  int64
 6   ClimateChange                    1117957 non-null  int64
 7   DamsQuality                      1117957 non-null  int64
 8   Siltation                        1117957 non-null  int64
 9   AgriculturalPractices            1117957 non-null  int64
 10  Encroachments                    1117957 non-null  int64
 11  IneffectiveDisasterPreparedness  1117957 non-null  int64
 12  DrainageSystems                  1117957 non-null  int64
 13  CoastalVulnerability             1117957 non-null  int64
 14  Landslides                       1117957 non-null  int64
 15  Watersheds                       1117957 non-null  int64
 16  DeterioratingInfrastructure      1117957 non-null  int64
 17  PopulationScore                  1117957 non-null  int64
 18  WetlandLoss                      1117957 non-null  int64
 19  InadequatePlanning               1117957 non-null  int64
 20  PoliticalFactors                 1117957 non-null  int64
 21  FloodProbability                 1117957 non-null  float64
dtypes: float64(1), int64(21)
memory usage: 187.6 MB

In [6]:
df.columns

Index(['id', 'MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'AgriculturalPractices', 'Encroachments',
       'IneffectiveDisasterPreparedness', 'DrainageSystems',
       'CoastalVulnerability', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
       'InadequatePlanning', 'PoliticalFactors', 'FloodProbability'],
      dtype='str')

In [7]:
df.isnull().sum()

id                                 0
MonsoonIntensity                   0
TopographyDrainage                 0
RiverManagement                    0
Deforestation                      0
Urbanization                       0
ClimateChange                      0
DamsQuality                        0
Siltation                          0
AgriculturalPractices              0
Encroachments                      0
IneffectiveDisasterPreparedness    0
DrainageSystems                    0
CoastalVulnerability               0
Landslides                         0
Watersheds                         0
DeterioratingInfrastructure        0
PopulationScore                    0
WetlandLoss                        0
InadequatePlanning                 0
PoliticalFactors                   0
FloodProbability                   0
dtype: int64

In [8]:
df = df.drop("id", axis=1)

In [9]:
df.columns

Index(['MonsoonIntensity', 'TopographyDrainage', 'RiverManagement',
       'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality',
       'Siltation', 'AgriculturalPractices', 'Encroachments',
       'IneffectiveDisasterPreparedness', 'DrainageSystems',
       'CoastalVulnerability', 'Landslides', 'Watersheds',
       'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss',
       'InadequatePlanning', 'PoliticalFactors', 'FloodProbability'],
      dtype='str')

In [10]:
X = df.drop("FloodProbability", axis=1)

y = df["FloodProbability"]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (894365, 20)
X_test : (223592, 20)
y_train: (894365,)
y_test : (223592,)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(X_train, y_train)

LinearRegression()

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [19]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
print(y_pred[:10])

[0.53392465 0.58491132 0.5225706  0.53937803 0.5791778  0.64672364
 0.46596818 0.4941741  0.4040769  0.4718653 ]

In [22]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0   0.560   0.533925
1   0.575   0.584911
2   0.510   0.522571
3   0.530   0.539378
4   0.590   0.579178
5   0.630   0.646724
6   0.455   0.465968
7   0.510   0.494174
8   0.395   0.404077
9   0.460   0.471865

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 0.01579247136376025
Mean Squared Error (MSE): 0.0004032065870905583
Root Mean Squared Error (RMSE): 0.0200800046586289
R² Score: 0.8448773362840328

In [24]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)

ridge_model.fit(X_train, y_train)

ridge_pred = ridge_model.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

ridge_mae = mean_absolute_error(y_test, ridge_pred)
ridge_rmse = mean_squared_error(y_test, ridge_pred) ** 0.5
ridge_r2 = r2_score(y_test, ridge_pred)

print("MAE:", ridge_mae)
print("RMSE:", ridge_rmse)
print("R2:", ridge_r2)

MAE: 0.015792472328693085
RMSE: 0.0200800046516062
R2: 0.8448773363925368

In [26]:
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=0.001)

lasso_model.fit(X_train, y_train)

lasso_pred = lasso_model.predict(X_test)

In [27]:
lasso_mae = mean_absolute_error(y_test, lasso_pred)
lasso_rmse = mean_squared_error(y_test, lasso_pred) ** 0.5
lasso_r2 = r2_score(y_test, lasso_pred)

print("MAE:", lasso_mae)
print("RMSE:", lasso_rmse)
print("R2:", lasso_r2)

MAE: 0.01608689375309151
RMSE: 0.020222456361976
R2: 0.8426685848296875

In [28]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression", "Lasso Regression"],
    "MAE": [mae, ridge_mae, lasso_mae],
    "RMSE": [rmse, ridge_rmse, lasso_rmse],
    "R2 Score": [r2, ridge_r2, lasso_r2]
})

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.015792  0.020080  0.844877
1   Ridge Regression  0.015792  0.020080  0.844877
2   Lasso Regression  0.016087  0.020222  0.842669

In [29]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression", "Lasso Regression"],
    "MAE": [mae, ridge_mae, lasso_mae],
    "RMSE": [rmse, ridge_rmse, lasso_rmse],
    "R2 Score": [r2, ridge_r2, lasso_r2]
})

print(results)

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.015792  0.020080  0.844877
1   Ridge Regression  0.015792  0.020080  0.844877
2   Lasso Regression  0.016087  0.020222  0.842669

In [30]:
import joblib

joblib.dump(model, "best_flood_model.pkl")

['best_flood_model.pkl']